# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMBL6LUvMxJMq_1xcElOfVvBVr_dtdRG
"""

names = input().split()
print(len(set(names)))

a = set(input().split())
b = set(input().split())
print(len(a ^ b))